### PR TITLE
add compat entries for stdlibs

### PR DESCRIPTION
**Pull request by tpapp**

### CODE REVIEW

**Comment by tpapp** [comment]
Meant to fix stalled registry PR https://github.com/JuliaRegistries/General/pull/94381. Please merge and try to reregister.

**Comment by tpapp** [comment]
Apparently [this does not work for Julia 1.0.](https://discourse.julialang.org/t/how-does-compat-requirement-changes-for-general-registry-affect-package-maintainers/104960/15?u=tamas_papp). 

Would requiring Julia 1.6 at least be considered?

**Comment by tpapp** [comment]
Friendly ping: if the approach is satisfactory, please merge and tag a release.

**Comment by willtebbutt** [comment]
Is this compat update stuff special? Usually we wouldn't tag a release unless a change is made to a file in `src`

**Comment by devmotion** [comment]
It's required for https://github.com/JuliaRegistries/General/pull/94381 which contains #228.

**Comment by willtebbutt** [comment]
Ohhhh sorry, I see. We previously bumped the patch version, so we just need to tag a release based on this PR.

**Pull request merged**
