### PR TITLE
Add tests and fixes for to_vec type-stability

### LINKED ISSUE #117: to_vec for non-real vectors is type-unstable
There are two separate problems that arise from `to_vec(x::AbstractVector)`'s use of the splatted form of `vcat`:

```julia
julia> using FiniteDifferences, Test

julia> @inferred to_vec([1.0+2.0im]) # splatting to vcat is not type-stable
ERROR: return type Tuple{Array{Float64,1},FiniteDifferences.var"#Vector_from_vec#36"{Array{Complex{Float64},1},Array{Array{Float64,1},1},Array{FiniteDifferences.var"#Complex_from_vec#34",1}}} does not match inferred return type Tuple{Union{Array{Any,1}, Array{Float64,1}},FiniteDifferences.var"#Vector_from_vec#36"{Array{Complex{Float64},1},Array{Array{Float64,1},1},Array{FiniteDifferences.var"#Complex_from_vec#34",1}}}
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at REPL[5]:1

julia> to_vec(ComplexF64[])[1] # splatting hits `vcat() => Any`
Any[]
```
For the latter case, see also https://github.com/JuliaLang/julia/issues/38532

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #117 as well as an issue with `to_vec(::Tuple)` being type-unstable.

### CODE REVIEW

**Review by willtebbutt — APPROVED** [review]
LGTM -- very nice. Thanks for sorting this out.

**Comment by sethaxen** [comment]
Thanks, I made a few additions to do the same thing for the backwards pass. In general `from_vec` is type-stable except in some cases for nested primals. That could be fixed in a future PR.

What is up with CI not running?

**Comment by sethaxen** [comment]
ooooh

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

Looks like it's time for GitHub Actions. I'll open a PR.

**Review by willtebbutt — APPROVED** [review]
Nice one. Approved subject to CI passing.

**Comment by oxinabox** [comment]
rebase for new CI?

**Comment by sethaxen** [comment]
CI is still pending review: https://github.com/JuliaDiff/FiniteDifferences.jl/pull/119

**Comment by sethaxen** [comment]
Unless someone objects, I'll merge this tomorrow.

**Review by oxinabox — APPROVED** [review]

**Pull request merged**
