### PR TITLE
Do not require that function arguments are ::Function.

### LINKED ISSUE #224: Argument limited to Functions
FiniteDifferences does not support objects that can be called without being a subtype of `Function`. It's a bit weird since Julia does not support multiple inheritances. Can the restriction `<: Function` be removed? If not it would be good to discuss the issue/workaround in the README.

```julia
using Interpolations
f = linear_interpolation(1:10, 1:10)
central_fdm(5, 1)(x -> f(x), 1.5)
# 1.000000000000018
central_fdm(5, 1)(f, 1.5)
#ERROR: MethodError: no method matching (::FiniteDifferences.AdaptedFiniteDifferenceMethod{5, 1, FiniteDifferences.UnadaptedFiniteDifferenceMethod{7, 5}})(::Interpolations.Extrapolation{Float64, 1, ScaledInterpolation{Float64, 1, Interpolations.BSplineInterpolation{Float64, 1, Vector{Float64}, BSpline{Linear{Throw{OnGrid}}}, Tuple{Base.OneTo{Int64}}}, BSpline{Linear{Throw{OnGrid}}}, Tuple{UnitRange{Int64}}}, BSpline{Linear{Throw{OnGrid}}}, Throw{Nothing}}, ::Float64)
#Closest candidates are:
#  (::FiniteDifferences.AdaptedFiniteDifferenceMethod)(::TF, ::Real) where TF<:Function
#   @ FiniteDifferences ~/.julia/packages/FiniteDifferences/zZFW0/src/methods.jl:191
#  (::FiniteDifferences.AdaptedFiniteDifferenceMethod{P, Q})(::TF, ::Real, ::Real) where {P, Q, TF<:Function}
#   @ FiniteDifferences ~/.julia/packages/FiniteDifferences/zZFW0/src/methods.jl:238
```

### PR DESCRIPTION
**Pull request by tpapp**
Fixes #224.

### CODE REVIEW

**Comment by tpapp** [comment]
Style note: tell me if the `struct` I added for testing should be somewhere else, happy to move it. It was moved up front to make tests work on 1.0.

**Comment by wesselb** [comment]
Hmmmm, @oxinabox or @willtebbutt, could either of you confirm whether this change could have any unintended consequences? I can't really recall if letting `f` be a function `Function` had a particular reason or not.

**Comment by willtebbutt** [comment]
I can't see it being a problem.

**Comment by oxinabox** [comment]
If tests pass then all is well

**Comment by oxinabox** [comment]
thanks

**Pull request merged**
