### PR TITLE
WIP: Adjoint problems

### PR DESCRIPTION
**Pull request by willtebbutt**
As @sethaxen pointed out in #133, #131 accidentally disabled a number of tests, and introduced a weird bug. This PR currently resolves the first of these problems, and I'm presently working on the second.

### CODE REVIEW

**Comment by willtebbutt** [comment]
@sethaxen could you confirm that this resolves the problem?

**Comment by sethaxen** [comment]
> @sethaxen could you confirm that this resolves the problem? I'm quite nervous about this because I don't really understand what's going on 😬 .

Well this is bizarre. Before it was correct for `Adjoint` and `Composite` differentials but conjugated for `Matrix`. Now this is correct for `Matrix` and `Adjoint` differentials but is conjugated for `Composite`

**Comment by willtebbutt** [comment]
Booooooooooooooooo. I wonder whether it ever consistent prior to #131 ?

**Comment by sethaxen** [comment]
Oooooh, not it wasn't. `Composite` has always been wrong for `Adjoint`. ChainRules worked around that by checking that the pullback produced the same output for `Matrix` and `Composite` cotangents but only passed the `Matrix` to `rrule_test`.
I think then this looks good to go.

**Review by sethaxen — APPROVED** [review]

**Pull request merged**
