### PR TITLE
Make to_vec output real for complex structured matrices

### LINKED ISSUE #84: to_vec gives complex vectors for most complex structured matrices
If I understand correctly `to_vec` should product a real vector and a function for reconstructing the structured matrix from it. Currently this doesn't work correctly for complex `Symmetric`, `Diagonal`, `Transpose`, and `Adjoint` matrices, which return complex vectors. e.g.:

```julia
julia> using FiniteDifferences, LinearAlgebra

julia> eltype_and_size(x) = (eltype(x), size(x));

julia> x = randn(ComplexF64, 3, 3);

julia> eltype_and_size(first(to_vec(x))) # this is fine
(Float64, (18,))

julia> eltype_and_size(first(to_vec(Diagonal(x))))
(Complex{Float64}, (9,))

julia> eltype_and_size(first(to_vec(Symmetric(x))))
(Complex{Float64}, (9,))

julia> eltype_and_size(first(to_vec(transpose(x))))
(Complex{Float64}, (9,))

julia> eltype_and_size(first(to_vec(adjoint(x))))
(Complex{Float64}, (9,))
```

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes #84

### CODE REVIEW

**Comment by willtebbutt** [comment]
Please bump patch to 0.10.1, then we're good to merge

**Comment by sethaxen** [comment]
Done!

**Comment by sethaxen** [comment]
Can this be merged?

**Comment by willtebbutt** [comment]
Please feel free to merge @sethaxen and register a new patch version :)

**Comment by sethaxen** [comment]
I do not seem to have permissions to merge the PR.

**Comment by willtebbutt** [comment]
Ohhhhhh okay. I'll merge for now and get that sorted at some point in the next couple of days.

**Comment by sethaxen** [comment]
Thanks, @willtebbutt!

**Pull request merged**
