### PR TITLE
Check that the derivative is nonnegative, and handle the case `q == 0`

### LINKED ISSUE #32: How do I choose method order to avoid NaN?
I am running into a situation where choosing specific orders for the Method is causing `NaN`s. Is this expected behaviour (e.g. resulting from some unfortunate math) or is this a bug?

In this example I am trying to take `n`th order directional derivatives. While silly, I've evaluated the `0`th order fdm, and on alternating method orders I'm getting `NaN`s:

```
@test sin(2.) ≈ central_fdm(1,0)(ϵ -> sin(2. +ϵ*1),0.) # Nan
@test sin(2.) ≈ central_fdm(2,0)(ϵ -> sin(2. +ϵ*1),0.) # true
@test sin(2.) ≈ central_fdm(3,0)(ϵ -> sin(2. +ϵ*1),0.) # Nan
@test sin(2.) ≈ central_fdm(4,0)(ϵ -> sin(2. +ϵ*1),0.) # true

@test cos(2.) ≈ central_fdm(2,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(3,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(4,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(5,1)(ϵ -> sin(2. +ϵ*1),0.) # true

@test -sin(2.) ≈ central_fdm(3,2)(ϵ -> sin(2. +ϵ*1),0.) # false but ok
@test -sin(2.) ≈ central_fdm(4,2)(ϵ -> sin(2. +ϵ*1),0.) # true
@test -sin(2.) ≈ central_fdm(5,2)(ϵ -> sin(2. +ϵ*1),0.) # true
@test -sin(2.) ≈ central_fdm(6,2)(ϵ -> sin(2. +ϵ*1),0.) # true
```

Note that I'm only observing this on the 0th order `fdm`.

### PR DESCRIPTION
**Pull request by wesselb**
Closes #32

### CODE REVIEW

**Comment by jessebett** [comment]
The default behaviour of `derivative(f,0)` should not be an assertion error, it should just return the function evaluation.

**Comment by willtebbutt** [comment]
> The default behaviour of derivative(f,0) should not be an assertion error, it should just return the function evaluation.

I can see the appeal. @wesselb any thoughts?

**Comment by wesselb** [comment]
Also sounds fair to me. @jessebett, how does the most commit look?

**Comment by nickrobinson251** [comment]
FYI I will register FiniteDifferences.jl as a a new package with a new UUID and version 0.1 (because renaming a package is hard/confusing/undefined behaviour AFAIU) 

Should I wait for this PR before doing that?

**Pull request merged**
