### PR TITLE
Only use the diagonal values in Diag, not the whole Matrix

### PR DESCRIPTION
**Pull request by mzgubic**

### CODE REVIEW

**Comment by mzgubic** [comment]
Oh, this breaks ChainRules tests

**Comment by oxinabox** [comment]
@willtebbutt

**Comment by willtebbutt** [comment]
Ah, yes, this relates to [this discussion](https://github.com/JuliaDiff/FiniteDifferences.jl/issues/132) -- I'm in favour of doing this, but we probably need to resolve some of the stuff in that conversation.

**Comment by mzgubic** [comment]
https://github.com/JuliaDiff/FiniteDifferences.jl/issues/186

**Pull request closed without merging**
